#!/usr/bin/env sh

# FIXME!!!: magic port number
address='http:/localhost:32323'
case $1 in
  hook )
    case $2 in
      -e )
	echo "enabling tmux state monitoring"
	curl "${address}/hook/enable/${3:-not-given/}"
	;;
      -d )
	echo "disable tmux state monitoring"
	curl "${address}/hook/disable/${3:-not-given/}"
	;;
      * )
	echo "invalid option ($*) for subcommand hook, must be (-e | -d)"
	;;
    esac
    ;;
  quickattach )       # fast asynchronous attach
    tmux switch-client -t __Tav__
    ;;
  attach )            # attach to tav window synchronized by tav daemon
    curl "${address}/attach/"
    ;;
  start )
    if curl "${address}/hello/tav/" &>/dev/null; then
      echo 'server already started'
      exit 1
    else
      echo 'start tav server'
      tav-core server
    fi
    ;;
  stop )
    echo 'stop tav server'
    curl "${address}/stop/"
    ;;
  restart )
    echo 'restart tav server'
    tav stop
    tav start
    ;;
  event )
    event=${2:-'null'}
    echo "send ${event} to server"
    curl "${address}/event/${event}/"
    ;;
  * )
    echo "unreconized argument: $*"
    ;;
esac
