#!/usr/bin/env sh

port=$(<~/.local/share/tav/port)
srv="http:/localhost:${port}"
case $1 in
  hook )
    case $2 in
      -e )
	echo "enabling tmux state monitoring"
	curl "${srv}/hook/enable/${3:-not-given/}"
	;;
      -d )
	echo "disable tmux state monitoring"
	curl "${srv}/hook/disable/${3:-not-given/}"
	;;
      * )
	echo "invalid option ($*) for subcommand hook, must be (-e | -d)"
	;;
    esac
    ;;
  quickattach )       # fast asynchronous attach
    tmux switch-client -t ___Tav_Yang___
    ;;
  attach )            # attach to tav window synchronized by tav daemon
    curl "${srv}/attach/"
    ;;
  start )
    if curl "${srv}/hello/tav/" &>/dev/null; then
      echo 'server already started'
      exit 1
    else
      echo 'start tav server'
      tav-core server
    fi
    ;;
  stop )
    echo 'stop tav server'
    curl "${srv}/stop/"
    ;;
  restart )
    echo 'restart tav server'
    tav stop
    tav start
    ;;
  event )
    event=${2:-'null'}
    echo "send ${event} to server"
    curl "${srv}/event/${event}/"
    ;;
  update | refresh )
    echo 'update tav inferface'
    curl "${srv}/event/refresh/"
    ;;
  * )
    echo "unreconized argument: $*"
    ;;
esac
