#!/usr/bin/env sh

action=$1

# FIXME!!!: magic port number
address='http:/localhost:32323'
case $action in
  attach )
    curl "${address}/attach/"
    ;;
  start )
    if curl "${address}/hello/tav/" &>/dev/null; then
      echo 'server already started'
    else
      echo 'start tav server'
      tav server
    fi
    ;;
  stop )
    echo 'stop tav server'
    curl "${address}/stop/"
    ;;
  restart )
    echo 'restart tav server'
    tavs stop
    tavs start
    ;;
  event )
    event=${2:-'null'}
    echo "send ${event} to server"
    curl "${address}/event/${event}"
    ;;
  * )
    echo 'unreconized argument'
    ;;
esac
