#!/usr/bin/env sh

action=$1

case $action in
  start )
    echo 'start tav server'
    tav server
    ;;
  stop )
    echo 'stop tav server'
    ;;
  restart )
    echo 'restart tav server'
    curl "${address}/stop/"
    tav server
    ;;
  event )
    event=${2:-'null'}
    echo "send ${event} to server"
    curl "${address}/event/${event}"
    ;;
esac
